def create_script(id):
    f = open("job%(id_)d.sh" % {'id_' : id}, 'w')
    f.write("#---------------------------Start program.job------------------------\n")
    f.write("#!/bin/bash\n")
    f.write("\n")
    f.write("# The name of the job, can be whatever makes sense to you\n")
    f.write("#$ -N TIM-%(c_)d\n" % {"c_" : id})
    f.write("\n")
    f.write("# Redirect output stream to this file.\n")
    f.write("#$ -o TIM_Yeah-%(c_)d\n" % {"c_" : id})
    f.write("\n")
    f.write("# Redirect error stream to this file.\n")
    f.write("#$ -e TIM_Oups-%(c_)d\n" % {"c_" : id})
    f.write("\n")
    f.write("# The batchsystem should use the current directory as working directory.\n")
    f.write("# Both files (output.dat and error.dat) will be placed in the current\n")
    f.write("# directory. The batchsystem assumes to find the executable in this directory.\n")
    f.write("#$ -cwd\n")
    f.write("\n")
    f.write("# This is the file to be executed.\n")
    f.write("./main.py --w "+str(id)+" --t 10000 --rec 1000 --repl 10")
    f.write("\n")
    f.write("#---------------------------End program.sge------------------------\n")
    f.close()

web_id = 0
while web_id < 178:
        create_script(web_id+1)
        web_id += 1

f = open("run.sh", 'w')
f.write("#---------------------------Start script------------------------\n")
f.write("#!/bin/bash\n")
f.write("\n")
f.write("# The SGE jobs to be executed.\n")
f.write("for ((  i = 0 ;  i < %(sim)d;  ++i  ))\n" % {"sim" : web_id})
f.write("do\n")
f.write("  qsub job$i.sh\n")
f.write("done\n")
f.write("\n")
f.write("#---------------------------End script------------------------\n")
f.close()
